const express = require("express")
const cors = require("cors")
const admin = require("./Models/r_admin.js")
const book = require("./Models/r_book.js")
const category = require("./Models/r_category.js")
const customer = require("./Models/r_customer.js")
const managecart = require("./Models/r_managecart.js")
const order = require("./Models/r_order.js")
const adminLogin = require("./Models/r_admin_Login.js")
const customerLogin = require("./Models/r_customer_Login.js")
const app= express()
app.use(cors())
app.use(express.json())
app.use("/backend/Images/",express.static("Images"))
app.use("/backend/manage_admin",admin)
app.use("/backend/manage_book",book)
app.use("/backend/manage_category",category)
app.use("/backend/manage_customer",customer)
app.use("/backend/manage_managecart",managecart)
app.use("/backend/manage_order",order)
app.use("/backend/admin_Login",adminLogin)
app.use("/backend/customer_Login",customerLogin)
app.listen("2009",()=>{
    console.log("server is started on port 2009")
})